// client/components/organisms/comment/comment.component.tsx
import React, { useState } from "react";

import { AthReplyComment, AthUpvoteComment } from "@client/components/molecules";
import { DateUtil } from "@client/utils";

import { ICommentUserUpvote } from "@global/types/comment.type";
import AthCommentReplies from "../comment-replies";

export interface IAthCommentProps extends React.HTMLAttributes<HTMLDivElement> {
	comment: ICommentUserUpvote;
}

const AthComment: React.FC<IAthCommentProps> = ({ comment, ...rest }: IAthCommentProps): JSX.Element => {
	const [derivedComment, setderivedComment] = useState<ICommentUserUpvote>(comment);

	return (
		<div className={`flex ${derivedComment.parentId ? "pt-5" : "pb-10"} last:pb-0`} {...rest}>
			<div className="flex flex-col shrink-0 mr-4">
				<img src={derivedComment.user!.picture} />
				{derivedComment.children && derivedComment.children.length > 0 ? (
					<div className="flex flex-1 divide-x">
						<div className="w-1/2" />
						<div className="w-1/2" />
					</div>
				) : (
					""
				)}
			</div>
			<div className="grow">
				<div className="flex items-center">
					<div className="font-bold">
						{derivedComment.user!.firstName} {derivedComment.user!.lastName}
					</div>
					<div className="mx-2">&#8226;</div>
					<div className="text-secondary-500 text-sm">{DateUtil.humanize(String(derivedComment.created))}</div>
				</div>
				<div className="font-light mb-4">{derivedComment.content}</div>
				<div>
					<AthUpvoteComment
						commentId={derivedComment.id}
						ownerId={derivedComment.user!.id}
						upvotes={derivedComment.upvotes || []}
						className="mr-4"
					/>
					{!derivedComment.parentId && (
						<AthReplyComment onComplete={setderivedComment} parentId={derivedComment.id} className="ml-4" />
					)}
				</div>
				{(derivedComment.children || []).length > 0 && <AthCommentReplies comment={derivedComment} />}
			</div>
		</div>
	);
};

export default AthComment;

// client/components/molecules/comment/comment.component.ts
import { DateUtil } from "@client/utils";

/** Custom Button Component extending the native HTMLElement */
export default class AthAddCommentModule extends HTMLElement {
	constructor() {
		super();
	}

	get comment(): Record<string, any> | null {
		return this.hasAttribute("comment") ? JSON.parse(decodeURIComponent(this.getAttribute("comment")!)) : null;
	}

	set comment(value: Record<string, any> | null) {
		value && JSON.stringify(value).length > 0
			? this.setAttribute("comment", JSON.stringify(value))
			: this.removeAttribute("comment");
	}

	public connectedCallback(): void {
		this.classList.add("flex", "items-start", "pb-10", "last:pb-0");
		this._render();
	}

	private _render(): void {
		const escapedJson: string = encodeURIComponent(JSON.stringify(this.comment!.upvotes));
		this.innerHTML = `
			<img src="${this.comment!.user.picture}" class="rounded-full w-9 mr-4"/>
			<div class="flex-0">
				<div class="flex items-center">
					<div class="font-bold">${this.comment!.user.firstName} ${this.comment!.user.lastName}</div>
					<div class="mx-2">&#8226;</div>
					<div class="text-secondary-500 text-sm">${DateUtil.humanize(this.comment!.created)}</div>
				</div>
				<div class="font-light mb-4">${this.comment!.content}</div>
				<div class="flex">
					<ath-upvote-comment
						commentId="${this.comment!.id}"
						ownerId="${this.comment!.user.id}"
						upvotes="${escapedJson}"
					>
					</ath-upvote-comment>
					<button is="ath-button" disabled secondary="true" small="true" class="ml-4">Reply</button>
				</div>
			<div>
		`;
	}
}
